version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum ".nvmrc" }}-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum ".nvmrc" }}-{{ checksum "package-lock.json" }}
      - run: npm run lint
      - run: npm run stylelint
      - run: npm run compile
